version: '3.8'

services:
  automated-azan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: automated-azan-main
    restart: unless-stopped
    environment:
      - LOG_FILE=/var/log/azan_service.log
      - TZ=Europe/Dublin
    volumes:
      - azan_logs:/var/log
      - azan_config:/app/config
      - ./adahn.config:/app/adahn.config:ro
    network_mode: host  # Required for Chromecast discovery
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: automated-azan-web
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
    ports:
      - "5000:5000"
    volumes:
      - azan_logs:/var/log
      - azan_config:/app/config
      - ./adahn.config:/app/adahn.config:ro
    depends_on:
      - automated-azan
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  azan_logs:
    driver: local
  azan_config:
    driver: local

networks:
  default:
    name: automated-azan-network
